INSERT INTO series (title, author_id, subgenre_id) VALUES ("His Dark Materials", 1, 1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("Harry Potter", 2, 2);
INSERT INTO books (title, year, series_id) VALUES ("The Golden Compass", 1989, 1);
INSERT INTO books (title, year, series_id) VALUES ("The Subtle Knife", 1990, 1);
INSERT INTO books (title, year, series_id) VALUES ("The Amber Spyglass", 1999, 1);
INSERT INTO books (title, year, series_id) VALUES ("Harry Potter and the Sorcerer's Stone", 1997, 2);
INSERT INTO books (title, year, series_id) VALUES ("Harry Potter and the Chamber of Secrets", 1998, 2);
INSERT INTO books (title, year, series_id) VALUES ("Harry Potter and the Prisoner of Azkaban", 1999, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Lyra", "Piss off", "Human", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Mrs. Coulter", "Die", "Human", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Will Parry", "I'm trying", "Human", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Roger", "My daemon is a rat", "Human", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Ron Weasley", "I hate spiders", "Human", 2, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Hermione Granger", "I'm smarter than you", "Human", 2, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Professor Quirrel", "Bitch I'm Voldemort", "Human", 2, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Harry Potter", "Boop", "Human", 2, 2);
INSERT INTO subgenres (name) VALUES ("Other universes");
INSERT INTO subgenres (name) VALUES ("Wizards");
INSERT INTO authors (name) VALUES ("Philip Pullman");
INSERT INTO authors (name) VALUES ("J.K. Rowling");
INSERT INTO character_books (character_id, book_id) VALUES (1 ,1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 1);
INSERT INTO character_books (character_id, book_id) VALUES (3, 1);
INSERT INTO character_books (character_id, book_id) VALUES (4, 1);
INSERT INTO character_books (character_id, book_id) VALUES (5, 1);
INSERT INTO character_books (character_id, book_id) VALUES (6, 1);
INSERT INTO character_books (character_id, book_id) VALUES (7, 1);
INSERT INTO character_books (character_id, book_id) VALUES (8, 1);
INSERT INTO character_books (character_id, book_id) VALUES (1, 2);
INSERT INTO character_books (character_id, book_id) VALUES (2, 2);
INSERT INTO character_books (character_id, book_id) VALUES (3, 2);
INSERT INTO character_books (character_id, book_id) VALUES (4, 2);
INSERT INTO character_books (character_id, book_id) VALUES (5, 2);
INSERT INTO character_books (character_id, book_id) VALUES (6, 2);
INSERT INTO character_books (character_id, book_id) VALUES (7, 2);
INSERT INTO character_books (character_id, book_id) VALUES (8, 2);
